### ISSUE TITLE
Support the Raspberry Pi 2

### ISSUE THREAD

**Issue by bskari** [bskari/pi-rc#14]
The Raspberry Pi changed how the DMA is initialized. This should detect if it's being run on a Pi 2 and use the new DMA. In the short term, it should detect if it's running on a Pi 2, issue an error, and exit.

**Comment by lavanoid** [comment]
:+1:

**Comment by bskari** [comment]
So, I copied some changes from another project, [rpitx](https://github.com/F5OEO/rpitx), to try and support the Pi 2. The problem is, I think the GPIO pins on my Pi 2 are dead, so I can't test this. Also, my Pi A+ USB port is dead, and I can't find my Pi Zero, so I can't even test that this works on the old version. If anyone has a working Pi and would like to test, I have a branch named `pi2` that I would love to get tested.

This is mostly a stop gap because I've gotten some requests for it though. I've been working on adding a Python interface to rpitx, and adding RC support as well. rpitx already does a lot more stuff than my library, and is better supported, so when I get that working, I'll probably move all support over to there.

**Comment by jcdickinson** [comment]
I'm going to be looking into using this when an RC is delivered. Still the same pin?

**Comment by bskari** [comment]
Yes, still the same pin. I just got an email from another user who said this didn't work for them, but it still works for their Pi 1, so I'm going to need to do some more testing.
