### ISSUE TITLE
Filter Required?

### ISSUE THREAD

**Issue by TheKitDev** [bskari/pi-rc#32]
Would this require some sort of 'filter' to be able to transmit Legally? I have heard from other people that it would transmit in the 3rd, 5th, 7th and 9th without one (which are essential bands)

**Comment by bskari** [comment]
Yeah this creates a lot of interference. I wrote this before I got my ham radio license and knew much about radio, but now that I have my license, I regret writing it. https://www.dk0tu.de/blog/2016/05/28_Raspberry_Pi_Lowpass_Filters/ looks to have a good guide.
